# Generated by Django 4.1.1 on 2022-09-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('average_rating', models.FloatField(verbose_name='average_rating')),
                ('isbn', models.CharField(max_length=150, verbose_name='isbn')),
                ('isbn13', models.CharField(max_length=150, verbose_name='isbn13')),
                ('language_code', models.CharField(max_length=10, verbose_name='language_code')),
                ('num_pages', models.IntegerField(verbose_name='num_pages')),
                ('ratings_count', models.BigIntegerField(verbose_name='ratings_count')),
                ('text_review_count', models.BigIntegerField(verbose_name='text_review_count')),
                ('publication_date', models.DateField(verbose_name='publication_date')),
                ('publisher', models.CharField(max_length=150, verbose_name='publiser')),
            ],
        ),
    ]
